FROM node:20-alpine AS base
WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/shared ./packages/shared
COPY apps/api ./apps/api
RUN npm install -g pnpm && pnpm install --frozen-lockfile && pnpm build
RUN pnpm deploy --filter=api --prod /prod/api

FROM node:20-alpine AS runner
ENV NODE_ENV=production
ENV PORT=3000
WORKDIR /app
COPY --from=base /prod/api .
EXPOSE 3000
CMD ["node", "dist/index.js"]
